source:             .
destination:        ./doc
safe:               false
include:            [".htaccess"]
exclude:            []
encoding:           "utf-8"
markdown_ext:       "markdown,mkdown,mkdn,mkd,md"
show_drafts:        null
limit_posts:        0
future:             true
unpublished:        false
markdown:           kramdown
highlighter:        rouge
lsi:                false
excerpt_separator:  "\n\n"
permalink:          date
paginate_path:      /page:num
timezone:           null
quiet:              false
default:            []

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
